#!/bin/sh

#https://www.sqlite.org/cgi/docsrc/finfo?name=misc/althttpd.c
#https://www.sqlite.org/cgi/docsrc/raw?ci=trunk&filename=misc/althttpd.c

fname=althttpd.c
url='https://www.sqlite.org/cgi/docsrc/raw?ci=trunk&filename=misc/althttpd.c'

curl -R -s -o _$fname "$url"
[[ -f $fname && ! $(diff $fname _$fname) ]] && rm _$fname || mv _$fname $fname
